import React from 'react';

import s from './numericButtons.module.scss';

export const NumericButtons = () => (
  <div className={s.numericButtons}>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      7
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      8
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      9
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      4
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      5
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      6
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      1
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      2
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      3
    </button>
    <button
      type="button"
      className={s.numericButtons__zeroBtn}
    >
      0
    </button>
    <button
      type="button"
      className={s.numericButtons__btn}
    >
      ,
    </button>
  </div>
);
